### PR TITLE
fix size check

### LINKED ISSUE #276: Segfault in expect on heisenberg size mismatch
``` julia
using Yao, YaoExtensions
circ = dispatch!(variational_circuit(4, 2), :random);
h = heisenberg(2);
expect(h, zero_state(4)=>circ)
```
This code causes segfault. Not very consistent, sometimes I need to do more work in repl before it crashes, sometimes just pasting it in fresh repl causes segfault. Also crashes only if operator size is bigger than state size.
Tried same code with `kron` as operator, it returns error about size mismatch.
Found by accident.
```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
[Full stacktrace](https://gist.github.com/RSBat/63a530aa75249eb44fe78b90fab28b89)

### PR DESCRIPTION
**Pull request by GiggleLiu**
fix https://github.com/QuantumBFS/Yao.jl/issues/276

### CODE REVIEW

File: src/abstract_block.jl [hunk 1]
```diff
@@ -5,16 +5,19 @@ using YaoBase, YaoArrayRegister, SimpleTraits
 
 Apply a block (of quantum circuit) to a quantum register.
 """
+function apply!(r::AbstractRegister, @nospecialize(b::AbstractBlock))
```
Comment (Roger-luo) [inline src/abstract_block.jl:8]: why do we need a `nospecialize` here?

**Comment by Roger-luo** [comment]
the doc tests fail because you changed the printings to 1.6, should change the that back. the doc test only runs on 1.5 at the moment.

Also I don't quite understand why this is causing that issue, I also can't reproduce the segment fault

File: src/abstract_block.jl (hunk 1 above)
Comment (GiggleLiu) [reply src/abstract_block.jl:8]: Intuitively there are many types feeding into this function, we do not need to recompile each of them. Which is better? I am not sure.

**Comment by GiggleLiu** [comment]
> the doc tests fail because you changed the printings to 1.6, should change the that back. the doc test only runs on 1.5 at the moment.

Yeah, but do we need to fix them for 1.5? We need to change it sooner or later. We can still tag a version without doctests pass.

> Also I don't quite understand why this is causing that issue, I also can't reproduce the segment fault

It does not produce error, this is an issue too.

**Comment by Roger-luo** [comment]
I don't understand what this fixes, it seems you are just forwarding `_apply` to `_apply_fallback`, this doesn't look like fixing anything to me. can you reproduce QuantumBFS/Yao.jl#276 ? and how to reproduce that?

**Comment by GiggleLiu** [comment]
> I don't understand what this fixes, it seems you are just forwarding `_apply` to `_apply_fallback`, this doesn't look like fixing anything to me. can you reproduce [QuantumBFS/Yao.jl#276](https://github.com/QuantumBFS/Yao.jl/issues/276) ? and how to reproduce that?

There are tests added for that. Before,
```julia
julia> using Yao

julia> apply!(rand_state(3), repeat(5,X, (2,3)))
ArrayReg{1, ComplexF64, Array...}
    active qubits: 3/3
```

After
```julia
julia> using Yao
[ Info: Precompiling Yao [5872b779-8223-5990-8dd0-5abbb0748c8c]

julia> apply!(rand_state(3), repeat(5,X, (2,3)))
ERROR: QubitMismatchError("register size 3 mismatch with block size 5")
Stacktrace:
 [1] _check_size(r::ArrayReg{1, ComplexF64, Matrix{ComplexF64}}, pb::RepeatedBlock{5, 2, XGate})
   @ YaoBlocks ~/.julia/dev/YaoBlocks/src/abstract_block.jl:332
 [2] apply!(r::ArrayReg{1, ComplexF64, Matrix{ComplexF64}}, b::AbstractBlock)
   @ YaoBlocks ~/.julia/dev/YaoBlocks/src/abstract_block.jl:9
 [3] top-level scope
   @ REPL[2]:1
```

**Comment by Roger-luo** [comment]
OK, why this fixes QuantumBFS/Yao.jl#276?

**Comment by GiggleLiu** [comment]
Now Yao will error you correctly
```julia
julia> using Yao, YaoExtensions
[ Info: Precompiling YaoExtensions [7a06699c-c960-11e9-3c98-9f78548b5f0f]

julia> circ = dispatch!(variational_circuit(4, 2), :random);

julia> h = heisenberg(2);

julia> expect(h, zero_state(4)=>circ)
ERROR: QubitMismatchError("register size 4 mismatch with block size 2")
Stacktrace:
  [1] _check_size(r::ArrayReg{1, ComplexF64, Matrix{ComplexF64}}, pb::RepeatedBlock{2, 2, XGate})
    @ YaoBlocks ~/.julia/dev/YaoBlocks/src/abstract_block.jl:332
  [2] apply!
    @ ~/.julia/dev/YaoBlocks/src/abstract_block.jl:9 [inlined]
  [3] expect(op::RepeatedBlock{2, 2, XGate}, reg::ArrayReg{1, ComplexF64, Matrix{ComplexF64}})
    @ YaoBlocks ~/.julia/dev/YaoBlocks/src/blocktools.jl:101
  [4] #126
    @ ~/.julia/dev/YaoBlocks/src/blocktools.jl:128 [inlined]
  [5] (::Base.MappingRF{YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, Base.BottomRF{typeof(Base.add_sum)}})(acc::Base._InitialValue, x::RepeatedBlock{2, 2, XGate})
    @ Base ./reduce.jl:93
  [6] _foldl_impl(op::Base.MappingRF{YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, Base.BottomRF{typeof(Base.add_sum)}}, init::Base._InitialValue, itr::Add{2})
    @ Base ./reduce.jl:58
  [7] foldl_impl(op::Base.MappingRF{YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, Base.BottomRF{typeof(Base.add_sum)}}, nt::Base._InitialValue, itr::Add{2})
    @ Base ./reduce.jl:48
  [8] mapfoldl_impl(f::YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, op::typeof(Base.add_sum), nt::Base._InitialValue, itr::Add{2})
    @ Base ./reduce.jl:44
  [9] mapfoldl(f::Function, op::Function, itr::Add{2}; init::Base._InitialValue)
    @ Base ./reduce.jl:160
 [10] mapfoldl
    @ ./reduce.jl:160 [inlined]
 [11] #mapreduce#218
    @ ./reduce.jl:287 [inlined]
 [12] mapreduce
    @ ./reduce.jl:287 [inlined]
 [13] #sum#221
    @ ./reduce.jl:501 [inlined]
 [14] sum(f::Function, a::Add{2})
    @ Base ./reduce.jl:501
 [15] expect
    @ ~/.julia/dev/YaoBlocks/src/blocktools.jl:128 [inlined]
 [16] #126
    @ ~/.julia/dev/YaoBlocks/src/blocktools.jl:128 [inlined]
 [17] (::Base.MappingRF{YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, Base.BottomRF{typeof(Base.add_sum)}})(acc::Base._InitialValue, x::Add{2})
    @ Base ./reduce.jl:93
 [18] _foldl_impl(op::Base.MappingRF{YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, Base.BottomRF{typeof(Base.add_sum)}}, init::Base._InitialValue, itr::Add{2})
    @ Base ./reduce.jl:58
 [19] foldl_impl(op::Base.MappingRF{YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, Base.BottomRF{typeof(Base.add_sum)}}, nt::Base._InitialValue, itr::Add{2})
    @ Base ./reduce.jl:48
 [20] mapfoldl_impl(f::YaoBlocks.var"#126#127"{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}}, op::typeof(Base.add_sum), nt::Base._InitialValue, itr::Add{2})
    @ Base ./reduce.jl:44
 [21] mapfoldl(f::Function, op::Function, itr::Add{2}; init::Base._InitialValue)
    @ Base ./reduce.jl:160
 [22] mapfoldl
    @ ./reduce.jl:160 [inlined]
 [23] #mapreduce#218
    @ ./reduce.jl:287 [inlined]
 [24] mapreduce
    @ ./reduce.jl:287 [inlined]
 [25] #sum#221
    @ ./reduce.jl:501 [inlined]
 [26] sum(f::Function, a::Add{2})
    @ Base ./reduce.jl:501
 [27] expect
    @ ~/.julia/dev/YaoBlocks/src/blocktools.jl:128 [inlined]
 [28] expect(op::Add{2}, plan::Pair{ArrayReg{1, ComplexF64, Matrix{ComplexF64}}, ChainBlock{4}})
    @ YaoBlocks ~/.julia/dev/YaoBlocks/src/blocktools.jl:136
 [29] top-level scope
    @ REPL[4]:1
```

That issue is caused by missing `_check_size` in both `Add` and `Repeat`. This is why I feel it is not guaranteed to check size correctly with the previous implementation, even though we have been careful to add size check when implementing a block.

**Comment by Roger-luo** [comment]
I see, it gives me a result somehow. LGTM

**Comment by GiggleLiu** [comment]
> I see, it gives me a result somehow. LGTM

I think the problem is, it shouldn't give you a result...
